### ISSUE TITLE
Laggy performance on Note 4

### ISSUE THREAD

**Issue by alexschled** [simplifycom/ink-android#1]
Hi,

I think simplify-ink is the best Android signature tool you can find. Thats why I'm using this in my new app. But i recognized a problem with the performance of the api, it's really laggy on using with the Samsung Note 4 (it doesn't matter if SPen or Finger). On my development devise the Nexus 4 it is running very smoothly and the signature looks great.

Do you think you can optimize the performance of your tool for the new Galaxy Note? Maybe the performance is laggy because of the resolution the phone has. 

Thank you

**Comment by nak5ive** [comment]
thanks for the report.
I've tested on the Nexus 5/6, HTC One, and Samsung S4/5. I haven't seen any lagging performance there. I don't have a Note 4 on hand to debug, so will have to see if I can find one. Does the problem exist in the sample app that ships with source? And which version (Android / Ink) are you targeting?

**Comment by alexschled** [comment]
Yes the problem exist with the sample app. I installed the last version of Android /Ink you can find on github on the nexus 5 and galaxy note 4. 

Here is a video, so you can see what I mean:
http://youtu.be/h9jvtvaKnrU

**Comment by siddii** [comment]
@alexschled - I tried the sample app on my Note 4 with AT&T's stock settings and it worked fine. I didn't see any sluggish performance with & without S-Pen. 

Is there something else in your device settings causing this?

**Comment by nak5ive** [comment]
Could not reproduce.
