### ISSUE TITLE
Unable to change color of stroke with setColor()

### ISSUE THREAD

**Issue by TheMaxCoder** [simplifycom/ink-android#10]
I am trying to change the color of the ink but `mInkView.setColor()` has no effect. I'm not using any flags or anything. in `xml` it looks like this

> <com.simplify.ink.InkView
>         android:id="@+id/ink"
>         android:layout_width="match_parent"
>         android:layout_height="match_parent"/>

and then in fragment 

>  mInkView = (InkView) view.findViewById(R.id.ink);
>  mInkView .setColor(getResources().getColor(R.color.colorAccent));
>  mInkView .setMinStrokeWidth(1.5f);
>  mInkView .setMaxStrokeWidth(6f);

Thanks

**Comment by rubixhacker** [comment]
I am unable to reproduce the issue, could you please provide more information about your environment? (Device, Version of Android, etc?)

**Comment by TheMaxCoder** [comment]
I have tested it on lollipop and kitkat, changing color has no affect, its always black. your able to change the color?

**Comment by rubixhacker** [comment]
Yes I am able to change the color. I have tested on KitKat, Lollipop, and Android N Preview 3. I am using android.R.color.holo_dark_red as the color.

Could it be an issue that R.color.colorAccent is not getting resolved to the proper color and is getting resolved to black?

**Comment by TheMaxCoder** [comment]
No I have tried it with multiple different colors and the result was same, well tomorrow I will create a sample project just to test ink in it and report back, thanks for your interest I really appreciate it :)

**Comment by TheMaxCoder** [comment]
the issue is with global declaration of ink, when I removed global declaration and declared ink as local variable it sets the color just fine, what could be the problem?

**Comment by TheMaxCoder** [comment]
the issue was within my own code, sorry i will close it now
