### ISSUE TITLE
It is creating only upper half  of the signature bitmap

### ISSUE THREAD

**Issue by chandan641989** [simplifycom/ink-android#14]
When i am converting the bitmap into base64 and then i am trying to see it as image on online converter, But its only showing me the upper half part of the signature not, full. 
Could you please help me out sir.

**Comment by nak5ive** [comment]
Can you try a different converter? It's not possible to diagnose if this is a problem with the SDK or the converter you are attempting to use.

**Comment by chandan641989** [comment]
Thanks for quick response. I am sorry i have created issue without investigation. ink-android library is working perfect. Actually logcat was not showing full log of the base64 encoded image, so i was trying to copy those  logs and converting into image. That is why it was showing half image.
