### ISSUE TITLE
Unable to download dependency files

### ISSUE THREAD

**Issue by hassanroid** [simplifycom/ink-android#17]
org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not GET 'https://dl.google.com/dl/android/maven2/com/simplify/ink/X.X.X/ink-X.X.X.pom'. Received status code 502 from server: Bad Gateway

It is giving the above error when ever i try to sync the project after adding this dependency. Kindly help

**Comment by nak5ive** [comment]
The version number in your `build.gradle` file needs to match the latest build
`implementation 'com.simplify:ink:1.0.2'`

**Comment by hassanroid** [comment]
Thank you sir. It's working now. But how could i know that i have to use this specific version 1.0.2 instead of 'X.X.X' (which i don't know what means)? i mean the you gave the dependency like this (implementation 'com.simplify:ink:X.X.X') not like this (implementation 'com.simplify:ink:1.0.2'). 
Anyway thanks for the reply and fix. im going to use your lib in my "Signature Maker" App on playstore having more than 80K+ downloads. :)

**Comment by rubixhacker** [comment]
![screen shot 2018-10-02 at 1 16 38 pm](https://user-images.githubusercontent.com/1776138/46368790-b7e44180-c646-11e8-92c2-7350a159fbfd.png)

The the blue badge shows the latest version and it updates automatically when we push a new version. You can also find the latest version under the releases tabs.

**Comment by hassanroid** [comment]
> ![screen shot 2018-10-02 at 1 16 38 pm](https://user-images.githubusercontent.com/1776138/46368790-b7e44180-c646-11e8-92c2-7350a159fbfd.png)
> 
> The the blue badge shows the latest version and it updates automatically when we push a new version. You can also find the latest version under the releases tabs.

Thank you :)
