### ISSUE TITLE
Cannot get bitmap with transparent background

### ISSUE THREAD

**Issue by niteshkhatri** [simplifycom/ink-android#3]
Hi guys. First of all thanks for a great library. Its responsive brush is really cool. And its really easy to get the bitmap. However, I am having a problem when I get the bitmap with transparent background. Instead of getting transparent background, I am getting black background. Please help me in this.

**Comment by nak5ive** [comment]
are you just trying to render it to a view, or export it to a file type?

**Comment by niteshkhatri** [comment]
I am saving it as file in sd-card, then showing it in ImageView.

**Comment by nak5ive** [comment]
If you are writing to a file, and you can see the signature on top of a black background, then you are able to extract the bitmap on a transparent background. I would instead check that you are saving the image correctly, as a PNG with a transparent layer.

**Comment by nak5ive** [comment]
Closing, as issue not believed to be with library, but rather how image was being persisted to disk.
