### ISSUE TITLE
Out of Memory exception

### ISSUE THREAD

**Issue by niteshkhatri** [simplifycom/ink-android#4]
Hi, you wrote a really nice library for drawing or signature. I have an issue. Sometimes I get OutOfMemory Exception when I clear my drawing and new bitmap is created.

```
java.lang.OutOfMemoryError
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:822)
at android.graphics.Bitmap.createBitmap(Bitmap.java:799)
at android.graphics.Bitmap.createBitmap(Bitmap.java:766)
at com.bolo.customview.InkView.clear(InkView.java:385)
at com.demo.FragmentDemoDraw.clearDrawing(FragmentDemoDraw.java:108)
```

I am getting this exception in below line.

```
mDebugBitmap = Bitmap.createBitmap(getWidth(), getHeight(), Bitmap.Config.ARGB_8888);
```

How can I prevent it? Please help me out.

**Comment by nak5ive** [comment]
are you holding previous bitmaps in memory before you attempt to clear the view?
for some high-res devices, these bitmaps can get pretty big. i wouldn't think clearing and replacing with new empty bitmaps would cause an out of memory, that is unless you were holding a reference to one outside of the view.

can you provide the context/use-case?
which device?

**Comment by nak5ive** [comment]
could you provide a device that is seeing this crash?
i am looking into some methods to reduce the allocated bitmap size.

**Comment by niteshkhatri** [comment]
@nak5ive No, I am not holding any Bitmaps before clearing the view. However, I am getting Bitmap from the view when the user saves his signature. If that Bitmap might be consuming the Memory, I will recycle that Bitmap once its task is done and make this Bitmap available for GC.

Moreover, please reduce the allocated bitmap size on your end, if possible.
