### ISSUE TITLE
'xdpi' and 'ydpi' 

### ISSUE THREAD

**Issue by youyou5920** [simplifycom/ink-android#5]
DisplayMetrics metrics = getContext().getResources().getDisplayMetrics();
    mDensity = (metrics.xdpi + metrics.ydpi) / 2f;
Could you tell me are 'xdpi' and 'ydpi' in these two pieces of code equal to  the width and the height in ios？ Thank you.

**Comment by nak5ive** [comment]
No. Xdpi/ydpi are density values, not dimensions. With Android, you never
know for sure what pixel density the screen will have, so careful measures
have to be taken to ensure the size of the stroke appears approximately the
same between devices.

For iOS, your screen densities are more finite (retina/non-retina). So you
would only need to account for those cases when drawing.
