### ISSUE TITLE
SVG Support?

### ISSUE THREAD

**Issue by ZakTaccardi** [simplifycom/ink-android#6]
Is it possible to export an .svg of the signature? or is bitmap only possible with this library?

If it is possible, please add documentation for it. If not, please add it!

Thanks!

**Comment by nak5ive** [comment]
No, it is not possible. The signature is being written to a bitmap and historical path data is thrown away. This helps reduce the growing memory footprint with keeping the signature data, as well as eliminating the overhead of re-drawing the entire set of paths on each screen refresh.

I hear you though. A vector alternative would be nice, but i can't say it's on the roadmap right now. If we attempt to implement VectorDrawable, we raise the minimum SDK level to 21, which isn't great. And if we go the route of SVG, we likely end up including another dependency, which we were trying to avoid.
