### ISSUE TITLE
Undo draw?

### ISSUE THREAD

**Issue by jaytj95** [simplifycom/ink-android#7]
Is there an option/flag to enable undos?

**Comment by nak5ive** [comment]
Currently, there is no option for an undo as it doesn't store historical
data. This is primarily to save on memory. You could implement it yourself
using the features provided, though. At the end of each draw, you could
grab the image and store it locally. Then an external button for undo could
grab the recent image and set it as the current bitmap on the view.

Something like this might work:

// register touch up motion event on inkview
Bitmap b = ink.getBitmap(); // called when touch up event
//persist bitmap

...

ink.clear();
ink.drawBitmap(b);

**Comment by jaytj95** [comment]
That's actually what I'm doing now!

Do you mind if I make a pull request to add this feature in there? Currently I'm using a stack to store the last 10 bitmaps to undo. It's not perfect but I'm working at it.

**Comment by nak5ive** [comment]
hmm. well, not sure we would roll that into a lightweight SDK. and i'm not sure keeping the stack in memory is a smart idea. these images can get big if you're not careful.

This feature might be better placed in a larger drawing library that declares Ink as a dependency.

I would say the purpose of this library is to add smooth drawing capabilities to a canvas, but not to become a full-featured drawing library.
